### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by denisalevi** [schapirolab/hip-sl#1]
Hi @DhairyyaS ,

I was just trying to run this model and couldn't get it working. I'm new to Go, so it might just be something obvious I'm missing. Or the recent updates to emergent are not compatible with your code (looks like GoGi was updated in April). Maybe you could help?

I followed these instructions: https://github.com/emer/emergent/wiki/Install, which recommend using Go modules during installation. I tried both, Go modules and installing through `GOPATH`, but both didn't work.

## Installation using Go modules

First I installed GoGi:
```
git clone https://github.com/goki/gi
cd gi/examples/widgets
go build
 ./widgets
```
Then Leabra:
```
git clone https://github.com/emer/leabra
cd leabra/examples/ra25
go build
./ra25 &
```

This worked fine, I could run the `widget` example from GoGi and the `ra25` example from Leabra.

But for hip-sl, this didn't work:
```
git clone https://github.com/schapirolab/hip-sl
cd hip-sl
go build
```

And I got a bunch of errors that the dependencies are not found (looking in `GOPATH` and `GOROOT`, but apperently not in `~/go/pkg/...` where the modules where installed). I don't know enough about Go to see how to fix this. Tried adding a `go.mod` file but that just ended up in different errors and I didn't pursue.

<details> <summary> Click for error output </summary> <p>

```
hip-sl.go:20:2: cannot find package "github.com/emer/emergent/emer" in any of:
        /usr/lib/go/src/github.com/emer/emergent/emer (from $GOROOT)
        /home/denis/go/src/github.com/emer/emergent/emer (from $GOPATH)
hip-sl.go:21:2: cannot find package "github.com/emer/emergent/env" in any of:
        /usr/lib/go/src/github.com/emer/emergent/env (from $GOROOT)
        /home/denis/go/src/github.com/emer/emergent/env (from $GOPATH)
hip-sl.go:22:2: cannot find package "github.com/emer/emergent/netview" in any of:
        /usr/lib/go/src/github.com/emer/emergent/netview (from $GOROOT)
        /home/denis/go/src/github.com/emer/emergent/netview (from $GOPATH)
hip-sl.go:23:2: cannot find package "github.com/emer/emergent/params" in any of:
        /usr/lib/go/src/github.com/emer/emergent/params (from $GOROOT)
        /home/denis/go/src/github.com/emer/emergent/params (from $GOPATH)
hip-sl.go:24:2: cannot find package "github.com/emer/emergent/prjn" in any of:
        /usr/lib/go/src/github.com/emer/emergent/prjn (from $GOROOT)
        /home/denis/go/src/github.com/emer/emergent/prjn (from $GOPATH)
hip-sl.go:25:2: cannot find package "github.com/emer/emergent/relpos" in any of:
        /usr/lib/go/src/github.com/emer/emergent/relpos (from $GOROOT)
        /home/denis/go/src/github.com/emer/emergent/relpos (from $GOPATH)
hip-sl.go:27:2: cannot find package "github.com/emer/etable/agg" in any of:
        /usr/lib/go/src/github.com/emer/etable/agg (from $GOROOT)
        /home/denis/go/src/github.com/emer/etable/agg (from $GOPATH)
hip-sl.go:28:2: cannot find package "github.com/emer/etable/eplot" in any of:
        /usr/lib/go/src/github.com/emer/etable/eplot (from $GOROOT)
        /home/denis/go/src/github.com/emer/etable/eplot (from $GOPATH)
hip-sl.go:29:2: cannot find package "github.com/emer/etable/etable" in any of:
        /usr/lib/go/src/github.com/emer/etable/etable (from $GOROOT)
        /home/denis/go/src/github.com/emer/etable/etable (from $GOPATH)
hip-sl.go:30:2: cannot find package "github.com/emer/etable/etensor" in any of:
        /usr/lib/go/src/github.com/emer/etable/etensor (from $GOROOT)
        /home/denis/go/src/github.com/emer/etable/etensor (from $GOPATH)
hip-sl.go:31:2: cannot find package "github.com/emer/etable/etview" in any of:
        /usr/lib/go/src/github.com/emer/etable/etview (from $GOROOT)
        /home/denis/go/src/github.com/emer/etable/etview (from $GOPATH)
hip-sl.go:32:2: cannot find package "github.com/emer/etable/split" in any of:
        /usr/lib/go/src/github.com/emer/etable/split (from $GOROOT)
        /home/denis/go/src/github.com/emer/etable/split (from $GOPATH)
hip-sl.go:34:2: cannot find package "github.com/emer/leabra/hip" in any of:
        /usr/lib/go/src/github.com/emer/leabra/hip (from $GOROOT)
        /home/denis/go/src/github.com/emer/leabra/hip (from $GOPATH)
hip-sl.go:35:2: cannot find package "github.com/emer/leabra/leabra" in any of:
        /usr/lib/go/src/github.com/emer/leabra/leabra (from $GOROOT)
        /home/denis/go/src/github.com/emer/leabra/leabra (from $GOPATH)
hip-sl.go:37:2: cannot find package "github.com/goki/gi/gi" in any of:
        /usr/lib/go/src/github.com/goki/gi/gi (from $GOROOT)
        /home/denis/go/src/github.com/goki/gi/gi (from $GOPATH)
hip-sl.go:38:2: cannot find package "github.com/goki/gi/gimain" in any of:
        /usr/lib/go/src/github.com/goki/gi/gimain (from $GOROOT)
        /home/denis/go/src/github.com/goki/gi/gimain (from $GOPATH)
hip-sl.go:39:2: cannot find package "github.com/goki/gi/giv" in any of:
        /usr/lib/go/src/github.com/goki/gi/giv (from $GOROOT)
        /home/denis/go/src/github.com/goki/gi/giv (from $GOPATH)
hip-sl.go:40:2: cannot find package "github.com/goki/ki/ki" in any of:
        /usr/lib/go/src/github.com/goki/ki/ki (from $GOROOT)
        /home/denis/go/src/github.com/goki/ki/ki (from $GOPATH)
hip-sl.go:41:2: cannot find package "github.com/goki/ki/kit" in any of:
        /usr/lib/go/src/github.com/goki/ki/kit (from $GOROOT)
        /home/denis/go/src/github.com/goki/ki/kit (from $GOPATH)
```

</p></details>

## Installation using `GOPATH`

Then I tried to install without Go modules by setting `GO111MODULE=off` and using `go get`:
```
go get github.com/goki/gi
cd $GOPATH/src/github.com/goki/gi
get ./...

go get github.com/emer/leabra
cd $GOPATH/src/github.com/emer/leabra/ra25
get ./...
```
This installed everything in `~/go/src/...` and running the `widget` and `ra25` examples ran find again but `hip-sl` not.
```
go get github.com/schapirolab/hip-sl
cd $GOPATH/src/github.com/schapirolab/hip-sl
get ./...
go build
```
This is the error I get:
```
# github.com/schapirolab/hip-sl
./hip-sl.go:754:28: invalid operation: ss.TestEnv.TrialName == "A" (mismatched types env.CurPrvString and string)
./hip-sl.go:1270:47: cannot use ss.TestEnv.TrialName (type env.CurPrvString) as type string in argument to dt.SetCellString
./hip-sl.go:1379:17: too many arguments in call to dt.WriteCSVRow
        have (*os.File, int, etable.Delims, bool)
        want (io.Writer, int, etable.Delims)
./hip-sl.go:1451:47: cannot use ss.TestEnv.TrialName (type env.CurPrvString) as type string in argument to dt.SetCellString
./hip-sl.go:1744:17: too many arguments in call to dt.WriteCSVRow
        have (*os.File, int, etable.Delims, bool)
        want (io.Writer, int, etable.Delims)
./hip-sl.go:1802:9: undefined: gi.NewWindow2D
```

Any idea how to get the model to run? Is this an issue on my side? 

Oh and your last commit added a 2GB file to this repository. Not sure if that was on purpose but took a while to clone :)

Cheers,
Denis

**Comment by DhairyyaS** [comment]
Hi Denis,

Thank you so much for bringing this issue up, and for the detailed error logs! The underlying problem that's causing these errors is that the version of Go Emergent that this model was written for was subsequently updated (along with some of its dependencies) after the model was published here. This broke some of the code since there were certain functions that now were expecting different parameters or certain struct methods had changed. You're absolutely right that this is a compatibility issue.

The easiest fix is to revert to older versions of Emergent/Leabra/Goki by reverting the cloned repos to previous commits. More details on this can be found here: https://stackoverflow.com/questions/2007662/rollback-to-an-old-git-commit-in-a-public-repo

I think this also requires switching off modules, which you've already done so just following the steps from the link should work!

My guess is that if you revert to versions from October/November 2019, that should do the trick and the model should build and run correctly.

I'm very interested in finding out if that works or not, and definitely let me know if you have any other questions/issues. If this works for you, I can add the right commit hashes to the readme and that would help clarify which version of emergent people should download to run the model in the future.

Also, yes last commit we added all the model output data files which we used to produce the plots in https://github.com/schapirolab/hip-sl/wiki/Results. You can definitely omit that by cloning the repo version with the hash 09ae0bc61f41a1922d73494371c9cdd726ca4786 !

Best,
Dhairyya

**Comment by denisalevi** [comment]
Hey Dhairyya,

thanks for your response! I played around with it for an afternoon and didn't get it to work. From what I understand, there is no easy way to install an old version of a Go package with correct dependencies (and their versions) without a Go versioning tool? I mean I did `git checkout` some older version of the Goki etc. but once I run `go ./...`, the newest versions of all dependencies are installed. And it is quite a mess, there are like 7 or 8 packages in goki and emer (go, ki, pi, etc.) and their older versions seem to have dependencies that need to be downgraded as well. And I just stopped at some point.

Instead I thought its probably easier to use Go modules in this repo and specify the exact versions in there, I mean that is what Go modules is for, a versioning system, right? But that needs some tinkering too and I didn't have the time to finish it. Currently the issue is that even if I specify versions of e.g. goki packages in `go.mod`, somehow I still end up installing the newest version somewhere during the dependency installation, which then give errors with `hip-sl`. One reason seems to be that older versions of goki packages don't have a `go.mod` file yet and end up just installing the newest version of their dependencies. So I tried to go through all goki / emergent packages and specify a commit that is compatible with `hip-sl` and also has a `go.mod` file. But I ran out of time. Not sure if this will go anywhere. And I will be on holidays now, so will look into it another time I guess.

If I'm doing this wrong or you see an easier way to get it to work, let me know.

Best,
Denis

**Comment by DhairyyaS** [comment]
Hi Denis,

Sorry for the delay in responding to this and thank you so much for trying out different solutions to the problem! 

I think you're right that setting up a Go mod correctly is a good way to solve this. Alternatively, I am also inclined to just fix all the broken code and update the model to run on the latest version of Emergent. That has the advantage of being more likely to work in the future as well so I am leaning towards doing that. I am adding this to my list and should be able to get to it sometime this week. Hopefully, by the time you are back from holiday, I should have a working version for you! I will let you know here once I have been able to fix the issue.

Enjoy your break :)

Best,
Dhairyya

**Comment by DhairyyaS** [comment]
Hi Denis,

I've finally been able to update the model to work with a newer version of emergent and have added a go.mod to stabilize compatibility. Hopefully, everything should work now. Let me know if you try it out and in case you have any trouble with it.

Best,
Dhairyya
